# Site settings
name: Fernando Marmolejo
title: Fernando Marmolejo | Software Developer 
description: Computer engineer working as a software developer
url: https://fermarval.github.com/
baseurl: ""
email: fmarvallejo@gmail.com
cover: https://fermarval.github.com/img/og.png
logo: https://fermarval.github.com/img/emojis/technologist.png
resume: https://fermarval.github.com/resume.pdf
social:
  - title: email
    url: mailto:fmarvallejo@gmail.com
  - title: twitter
    url: https://twitter.com/femarval
  - title: instagram
    url: https://instagram.com/femarval
  - title: codepen
    url: http://codepen.io/fermarval
  - title: github
    url: https://github.com/fermarval
  - title: linkedin
    url: https://www.linkedin.com/in/fmarmolejo

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
